[package]
name = "jsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxc = { version = "0.7.0" }
oxc_ast = { version = "0.7.0", features = ["serde"] }
serde = "1.0.196"
serde_json = "1.0.113"
